/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plter_game2d_display_DisplayObjectContainer */

#ifndef _Included_com_plter_game2d_display_DisplayObjectContainer
#define _Included_com_plter_game2d_display_DisplayObjectContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plter_game2d_display_DisplayObjectContainer
 * Method:    nativeAddChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_DisplayObjectContainer_nativeAddChild
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_plter_game2d_display_DisplayObjectContainer
 * Method:    nativeRemoveChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_DisplayObjectContainer_nativeRemoveChild
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
