/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plter_game2d_display_Label */

#ifndef _Included_com_plter_game2d_display_Label
#define _Included_com_plter_game2d_display_Label
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plter_game2d_display_Label
 * Method:    createNativeObjectWithString
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_com_plter_game2d_display_Label_createNativeObjectWithString
  (JNIEnv *, jobject, jstring, jstring, jfloat);

/*
 * Class:     com_plter_game2d_display_Label
 * Method:    nativeSetString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_Label_nativeSetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_plter_game2d_display_Label
 * Method:    nativeSetFontName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_Label_nativeSetFontName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_plter_game2d_display_Label
 * Method:    nativeSetFontSize
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_Label_nativeSetFontSize
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
