/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plter_game2d_display_Image */

#ifndef _Included_com_plter_game2d_display_Image
#define _Included_com_plter_game2d_display_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plter_game2d_display_Image
 * Method:    createNativeObjectWithFileNameAndRect
 * Signature: (Ljava/lang/String;FFFF)J
 */
JNIEXPORT jlong JNICALL Java_com_plter_game2d_display_Image_createNativeObjectWithFileNameAndRect
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_plter_game2d_display_Image
 * Method:    createNativeObjectWithFileName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_plter_game2d_display_Image_createNativeObjectWithFileName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
