/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plter_game2d_display_Sprite */

#ifndef _Included_com_plter_game2d_display_Sprite
#define _Included_com_plter_game2d_display_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_plter_game2d_display_Sprite
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_plter_game2d_display_Sprite_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_plter_game2d_display_Sprite
 * Method:    nativeSetContentSize
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_plter_game2d_display_Sprite_nativeSetContentSize
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
